config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'topics#index'
  get '/posts/index'
  get '/posts', to: 'posts#show_all'
  resources :topics do
    resources :posts do
      resources :comments
      resources :ratings
    end
  end
  resources :tags
  post '/:topic_id/post/:id/mark_read', to: 'posts#mark_post_read'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :topic
  belongs_to :user
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :index, :create, :destroy]
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end
  def show
    @comment = @post.comments.find(params[:id])
  end
  def index
    @comments = @post.comments.find(params[:id])
  end
  def create
    @comment = @post.comments.new(comment_params)
    @comment.topic_id = @topic.id
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to topic_post_path(@topic, @post)
    else
      flash[:notice] = "Comments should not be empty!"
      redirect_to topic_post_path(@topic, @post)
    end
  end
  def update
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to topic_post_path(@topic, @post)
    else
      render :edit
    end
  end
  def edit
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to topic_post_path(@topic, @post)
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
  def set_comment
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% @post.comments.each do |comment| %>
  <p>
    <% unless !comment.persisted? %>
      <strong>Comment by <%= comment.user.email %></strong>
      <%= comment.comment %>
      <% if can? :manage, comment %>
        <%= link_to "Edit", edit_topic_post_comment_path(topic_id: @topic, post_id: @post, id: comment ), class: "btn btn-secondary" %>
      </p>
        <% end %>
    <% end %>
<% end %>
<h3>Add a comment:</h3>
<%= form_with model: [ @topic, @post, comment ] do |form| %>
  <p>
    <%= form.text_area :comment, class:"form-control" %>
  </p>
  <p>
    <%= form.submit "Add Comment", class:'btn btn-dark'%>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <% @post.comments.each do |comment| %>
    <p>
      <% unless !comment.persisted? %>
        <strong>Comment by <%= comment.user.email %></strong>
        <%= comment.comment %>
      <% end %>
  <% end %>
<%= form_with model: [ @topic, @post, @comment ] do |form| %>
  <p>
    <%= form.text_area :comment, class:"form-control" %>
  </p>
  <p>
    <%= form.submit "Update Comment", class:'btn btn-dark'%>
  </p>
<% end %>
</div>