config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'topics#index'
  get '/posts/index'
  get '/posts', to: 'posts#show_all'
  resources :topics do
    resources :posts do
      resources :comments
      resources :ratings
    end
  end
  resources :tags
  post '/:topic_id/post/:id/mark_read', to: 'posts#mark_post_read'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  validates :title, presence: true
  validates :post, presence: true, length: { minimum: 10 }
  paginates_per 10
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
     if @topic.save
       format.html { redirect_to @topic, success: "Topics created Succesfully" }
       format.js
     else
       format.html { render :new }
     end
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, info: "Topics Updated!"
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @topic.destroy
    redirect_to root_path, warning: "Topic Deleted successfully!!"
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :post, :tag)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for( @topic) do |form| %>
  <br class="container form-group">
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control" %>
    <% topic.errors.full_messages_for(:title).each do |message| %>
      <div style="color:#ff0000;"><%= message %></div>
    <% end %>
  </div>
  </br>
  <div class="field form-group">
    <%= form.label :created_by_and_date %><br>
    <%= form.text_area :post, class:"form-control"%><br>
    <% topic.errors.full_messages_for(:post).each do |message| %>
      <div style="color:#ff0000;"><%= message %></div>
    <% end %>
  </div>
<div>
    <%= form.submit class:'btn btn-dark'%>
<% end %>
</div>

app/views/topics/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Topics', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'New Topic', new_topic_path, class:'nav-link'  %>
          </li>
<!--          <li class="nav-item">-->
            <%#= link_to 'Create Tag', new_tag_path, class:'nav-link'%>
<!--          </li>-->
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link'%>
          </li>
          <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:'nav-link'%>
        </li>
          <% end %>
       </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/topics/create.js.erb
//$("#newtopic").modal('hide');
//$(".topic_title").val('');
//$(".topic_post").val('');

//$("#topic_show").prepend('<%= j render @topic.posts %>');
console.log('');

app/views/topics/destroy.js.erb
$('.delete_itemm').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
});

app/views/topics/edit.html.erb
<div class="container">
<h3 class="display-4">Edit Post</h3>
<%= render "form", topic: @topic %>
</br>
  <%= link_to "Home", topics_path, class:"btn btn-info" %>
</div>

app/views/topics/index.html.erb
<ul>
  <% if user_signed_in? %>
    <p class="display-4">Topic Are Here!!!</p>

  <% @topics.each do |article| %>
    <li class="list-group-item">
          <h6><%= article.title%></h6>
      <%= article.post %>
      <%= link_to "Show" , topic_posts_path(article), class: "btn btn-primary"%>
      <%= link_to "Edit", topic_path(article), class: "btn btn-secondary" %>

      <% end %>
    </li>
  <% else %>
    </br>
    <p class="display-4">Log in to Continue!</p>
    <%= link_to 'Sign Up', new_user_registration_path, class:'btn btn-outline-dark' %>
    <%= link_to 'Sign In', new_user_session_path, class:'btn btn-outline-primary'%>
  </li>
  <% end %>
<br>
  <script>
      $(document).ready(function (){
          $('p').css('color', 'default');
      })
  </script>
  <%#= javascript_pack_tag 'intro' %>
  <%= will_paginate @topics %>
</ul>

app/views/topics/new.html.erb
<div class="container">
<h3 class="display-4">New Topic</h3>
<%= render "form", topic: @topic %>
  </br>
  <%= link_to "Home", topics_path, class:"btn btn-info" %>
</div>

app/views/topics/show.html.erb
<div class= "container", id="topic_show">
<h1><%= @topic.title %></h1>
  <h6>created <%= time_ago_in_words(@topic.created_at) %> ago</h6>
<p><%= @topic.post %></p>
&ensp; <%= link_to "Edit", edit_topic_path(@topic), class: "btn btn-secondary" %> |
&ensp;<%= link_to "Destroy", topic_path(@topic),
                  method: :delete,
                  data: { confirm: "Are you sure?" },:remote => true, class: "btn btn-danger" %> |


<%= link_to "Home", topics_path, class:"btn btn-info"%>
</div>