config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'topics#index'
  get '/posts/index'
  get '/posts', to: 'posts#show_all'
  resources :topics do
    resources :posts do
      resources :comments
      resources :ratings
    end
  end
  resources :tags
  post '/:topic_id/post/:id/mark_read', to: 'posts#mark_post_read'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
  # has_many :opinions, class_name: "Comment", dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  validates :content, presence: true, length: { maximum:20 }
  has_one_attached :image
  # validates :image, presence: true
  belongs_to :user
  has_and_belongs_to_many :users, join_table: :post_users_read_status
  accepts_nested_attributes_for :tags
  # def tags_for_form
  #   collection = tags.where(post_id: id)
  #   collection.any? ? collection : tags.build
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_and_belongs_to_many :read_posts, class_name: "Post", join_table: :post_users_read_status
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:index, :show, :update, :create, :destroy, :edit]
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token
  def new
    @posts = Post.all
  end
  def index
    @posts = @topic.posts.paginate(page: params[:page], per_page: 10)
    @readpostids = current_user.read_post_ids
  end
  def show
    @post = @topic.posts.find(params[:id])
  end
  def update
    @post = @topic.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to topic_post_path(@topic, @post)
    else
      render :edit
    end
  end
  def edit
    @post = @topic.posts.find(params[:id])
  end
  def create
    @post = @topic.posts.new(post_params)
    @post.user_id = current_user.id
    respond_to do |form|
    if @post.save
      form.js
      form.html { redirect_to topic_post_path(@topic, @post), success: "Post created Succesfully" }
    else
      flash[:danger] = "Should not exceed 20 characters!"
      form.html { redirect_to topic_posts_path(@topic, @post) }
      end
    end
  end
  def destroy
    @post = @topic.posts.find(params[:id])
    @post.user_id = current_user.id
    @post.destroy
    redirect_to topic_posts_path(@topic, @post)
  end
  def mark_post_read
    set_post
    begin
      @post.user_ids = @post.user_ids.append(current_user.id)
      @message = 'Post Marked Read'
    rescue => error
      @message = error.message
    end
    respond_to do |f|
      f.json { render json: @message, status: :ok }
    end
  end

  def show_all
    @topic = Topic.all
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, tag_ids:[], tags_attributes:  [:tag])
  end
  def set_post
    @topic = Topic.find(params[:topic_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for  [ @topic, @topic.posts.build ], remote: true do |form| %>
  <div class="container form-group">
    <%= form.text_area :content, class:"form-control" %>
    </br>
    <%= form.label :Add_Photo %>
    <%= form.file_field :image %>
    </br>
    </br>

    <%= form.label :Select_Tag %>
    <%= form.select(:tag_ids, Tag.all.collect {|t| [t.tag, t.id] }, { :prompt => "Please select"},
                 { :multiple => true, :size => 5 }) %>
    <%=  %>
    </br>
    </br>
    <%#= form.fields_for :tags, form.object.tags.build do |f| %>
      <%#= f.label :New_tag? %>
      <%#= f.text_field :tag, class:"form-control" %>
    <%# end %>
    <%# Tag.all.each do |list| %>
    <%#= check_box_tag "post[tag_ids][]", tag_ids %>
      <%#= list.tag_ids %>
      <%# end %>
  </div>
  <div>
    <%= link_to "Create new Tag", new_tag_path, class:"btn btn-light" %>
    </br>
    </br>
    <%= form.submit class:'btn btn-dark', remote: true %>
    <%#= link_to "Create new Tag", new_tag_path, class:"btn btn-light" %>
<% end %>
</div>

app/views/posts/_post.html.erb
<p>

  <%= post.content %>
  (<%= @topic.title %>)
</br>
<% if post.ratings.count.zero? %>
  <h6>Not Rated Yet</h6>
  <% else %>
  <h6>Rated <%= post.ratings.average(:rate) %></h6>
  <% end %>
</p>

<p>
  <%= link_to 'Read the Post', [post.topic, post], class: "btn btn-primary" %>
</p>


<!--<script type= "text/javascript">-->
<!--  $(document).ready(function () {-->
<!--      if(!(<%#= current_user.read_post_ids.include? @post.id %>)) {-->
<!--          $ajax({-->
<!--              url: "/<%= /topics/@topic.id%>/posts/<%= @post.id %>/mark_read",-->
<!--              type: "POST",-->
<!--              date: {},-->
<!--              complete: function (resp) {-->

<!--              }-->
<!--          });-->
<!--      }-->
<!--  });-->
<!--</script>-->

app/views/posts/create.js.erb
alert('Post Created Successfully')

app/views/posts/edit.html.erb
<div class="container">
  <h3 class="display-4">Edit Post</h3>
<%= form_with model: [@topic, @post ] do |form| %>
  <br class="container form-group">
  <div>
    <%= form.text_area :content, class:"form-control" %>
  </br>
    <%= form.label :Add_Photo  %>
    <%= form.file_field :image %>
  </br>
    </br>
    <%= form.label :Select_Tag %>
    <%= form.select(:tag_ids, Tag.all.collect {|t| [t.tag, t.id] }, { :prompt => "Please select"},
                    { :multiple => true, :size => 5 }) %>
    <%#= Tag.all.each do |list| %>
      <%#= check_box_tag "topic" %>
      <%#= list.tag %>
    <%# end %>
  </div>
  </br>
  <div>
    <%= form.submit class:'btn btn-dark'%>
<% end %>
  <%= link_to "Back", topic_post_path, class:"btn btn-light" %>
</div>

app/views/posts/index.html.erb
<div class= "container" id="new-post">

  <% if @posts.count.zero? %>
    <p class="display-4">No Post To Show :(</p>
    <% else %>
  <p class="display-4">All the Posts Of <%= @topic.title %></p>
  <% end %>
<!--  <strong><%#=  render @topic.posts %></strong>-->
  <% @posts.each do |post| %>
  <%= post.content %>
  (<%= @topic.title %>)
  </br>
    <% if @readpostids.include? post.id %>
     <h6 style="color:green"> read</h6>
    <% else %>
      <h6 style="color:red">not read</h6>
    <% end %>
  <% if post.ratings.count.zero? %>
    <h6>Not Rated Yet</h6>
  <% else %>
    <h6>Rated <%= post.ratings.average(:rate) %></h6>
  <% end %>
  </p>

  <p>
    <%= link_to 'Read the Post', [post.topic, post], class: "btn btn-primary" %>
  </p>

<% end  %>
  <%= will_paginate @posts %>

  <h2 class="display-4">Add a Post</h2>
  <%= render 'posts/form' %>
  </br>

  <%= link_to "Home", topics_path, class:"btn btn-info"%>

</div>

app/views/posts/new.html.erb
<div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
  <div class="accordion-body">
    <strong><%= render @topic.posts %></strong>
  </div>
</div>

app/views/posts/show.html.erb
</br>
<div class="container" id="new-post">
  <h2><%= @topic.title %></h2>
  <h6>Post Created by <%= @post.user.email  %> <%= time_ago_in_words(@post.created_at) %> ago</h6>
  <% if @post.ratings.count.zero? %>
    <h6>Not Rated Yet</h6>
    <% else %>
  <h6>Average Rating by users <%= @post.ratings.average(:rate) %></h6>
    <% end %>
    <h6 style="color:red">
  <% @post.tags.each do |tag| %>
    <%= tag.tag %>
    <% end %>
    </h6>
  <h5><%= @post.content %></h5>
  </br>
  <% if @post.image.present? %>
  <%= image_tag(@post.image, :alt => "rss feed", :height =>"320", :width => "320") %>
    </br>
    </br>
    <% end %>
  <% if can? :update, @post %>
<%= link_to "Edit", edit_topic_post_path, class: "btn btn-secondary" %>
    <% end %>
  <% if can? :destroy, @post %>
<%= link_to 'Delete Post', topic_post_path(@topic, @post),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
  </br>
  </br>
  <% @post.ratings.each do |comment| %>
    <p>
      <% unless !comment.persisted? %>
        <strong>Ratings</strong>
        <%= comment.rate %>
        </p>
      <% end %>
  <% end %>

  <%= render 'comments/form', comment: @post.comments.build %>
  <%= render 'ratings/form', rating: @post.ratings.build %>
  <%= link_to "Back", topic_posts_path(@topic), class: "btn btn-secondary" %>
  <%= link_to "Home", topics_path, class:"btn btn-info" %>
</div>

<script type= "text/javascript">
    $(document).ready(function () {
        if(!(<%= current_user.read_post_ids.include? @post.id %>)) {
            $.ajax({
                url: "/<%= @topic.id%>/post/<%= @post.id %>/mark_read",
                type: "POST",
                date: {},
                complete: function (resp) {
                }
            })
        }
    });
</script>

app/views/posts/show_all.html.erb
<% @posts.each do |f| %>
<%= f.content %></br>
  <% end %>
<%= paginate @posts %>